using System.Collections;
using Unity.Collections;
using UnityEngine;
using System;
using Cysharp.Threading.Tasks;
using Player.Controller;

public interface IThreadThrower
{
    /// <summary>
    /// 실이 Exist상태일 때, 사라질지 말지 확인하는 함수
    /// </summary>
    /// <returns></returns>
    bool IsExpired();
}

public enum ThrowThreadState
{
    Idle,
    Throwing,
    Exist,
    Deleting
}

public enum ThreadType
{
    Red,
    Blue
}

public abstract class ThrowThread : Thread, IThreadThrower
{
    [Header("실 종류")]
    [SerializeField] private ThreadType _threadType;
    [Header("목표 지점")]
    public Transform targetTransform;
    public Vector3 targetPos;
    [Header("한계 거리")]
    [SerializeField] protected float limitDistance = 5f;
    [Header("속도")]
    [SerializeField] private float _throwSpeed = 20f;
    [Header("빗맞았을 때 연출")]
    [SerializeField] private float _fallSpeed = 10f;

    protected PlayerController _player;
    protected ThrowThreadState _state;
    protected IClickInteractableToggle clickable;
    private int maxSegmentCount;
    private Vector3 prevNodePos;

    /* UI관련 */
    public event Action OnConnected;
    public event Action OnDisconnected;

    public void SetStart(Transform transform)
    {
        _startTransform = transform;
    }

    protected override void Initialize()
    {
        _lineRenderer = GetComponent<LineRenderer>();
        _player = _startTransform.GetComponent<PlayerController>();
        InitThread();
    }
    
    /* ✨ 수정됨: 캐싱된 마우스 위치(targetPosition)를 매개변수로 받습니다. */
    public void ClickEvent(Vector2 targetPosition)
    {
        switch (_state)
        {
            case ThrowThreadState.Idle:
                if (CanThrow())
                {
                    // ✨ 매개변수로 받은 위치를 StartThrowing으로 넘겨줍니다.
                    StartThrowing(targetPosition);
                }
                break;
            case ThrowThreadState.Exist:
                StartDeleting();
                break;
            case ThrowThreadState.Throwing:
            case ThrowThreadState.Deleting:
                break;
        }
    }

    protected virtual bool CanThrow() => true;

    protected override void UpdateThread()
    {
        // [안전장치] NativeArray 메모리가 해제된 상태라면 연산을 차단합니다.
        if (!segments.IsCreated) return;

        if (_state == ThrowThreadState.Exist)
        {
            // 연결 도중 타겟이 예기치 못하게 파괴된 경우 처리
            if (targetTransform == null)
            {
                OnDisconnected?.Invoke();
                StartDeleting();
                return;
            }

            if (IsExpired())
            {
                OnDisconnected?.Invoke();
                StartDeleting();
                return;
            }
            UpdateThreadVisualization();
        }
        else if (_state == ThrowThreadState.Deleting)
        {
            // 원래의 자연스러운 낙하 연출 유지 (_endTransform 널 체크만 추가)
            if (targetTransform == null && _endTransform != null)
            {
                _endTransform.position += _gravity * Time.deltaTime * 0.5f;
            }

            UpdateThreadVisualization();
        }
    }

    protected virtual void UpdateThreadVisualization()
    {
        UpdateSegments();
    }

    protected void InitThread()
    {
        // [안전장치] 자식으로 들어갔다가 타겟과 함께 파괴된 경우 원천 복구
        if (_endTransform == null)
        {
            GameObject autoGeneratedEnd = new GameObject($"[{gameObject.name}]_EndTransform_Recovered");
            _endTransform = autoGeneratedEnd.transform;
        }
        _endTransform.SetParent(null); // 부모 관계 초기화

        if (segments.IsCreated)
        {
            _currentJobHandle.Complete();
            segments.Dispose();
        }
        segmentCount = 2;
        _endTransform.position = _startTransform.position;
        Vector3 dir = (targetPos - _startTransform.position).normalized;
        float dist = Vector3.Distance(_startTransform.position, targetPos);
        if (dist > limitDistance)
        {
            targetPos = _startTransform.position + dir * limitDistance;
        }
        // targetPos 보정
        maxSegmentCount = (int)((_startTransform.position - targetPos).magnitude * 4);

        maxSegmentCount = Mathf.Max(maxSegmentCount, 2);
        _segmentPositions = new Vector3[maxSegmentCount];
        segments = new NativeArray<Segment>(maxSegmentCount, Allocator.Persistent);
        for (int i = 0; i < segmentCount; i++)
        {
            Vector2 pos = _startTransform.position;
            segments[i] = new Segment(pos);
        }
        _lineRenderer.positionCount = segmentCount;
        _lineRenderer.SetPositions(_segmentPositions);
    }

    void NormalizeSegments()
    {
        if (!segments.IsCreated) return;

        for (int i = 0; i < maxSegmentCount; i++)
        {
            float t = (float)i / (maxSegmentCount - 1);
            Vector3 pos = Vector3.Lerp(_startTransform.position, targetPos, t);
            segments[i] = new Segment(pos);
        }
    }

    void AddSegments()
    {
        if (_endTransform == null || !segments.IsCreated) return;

        float dist = Vector3.Distance(prevNodePos, _endTransform.position);

        if (dist >= segmentDist)
        {
            segments[segmentCount] = new Segment(_endTransform.position);
            segmentCount++;

            prevNodePos = _endTransform.position;
        }
    }

    /* ✨ 수정됨: ClickEvent로부터 넘어온 마우스 위치를 매개변수(mousePos)로 받습니다. */
    protected void StartThrowing(Vector2 mousePos)
    {
        _lineRenderer.enabled = true;
        _state = ThrowThreadState.Throwing;

        // ✨ 삭제됨: 실시간으로 마우스 위치를 구하던 기존 코드는 더 이상 사용하지 않습니다.
        // Vector2 mousePos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
        
        Collider2D hit = Physics2D.OverlapPoint(mousePos, LayerMask.GetMask("Interaction"));
        float dist = Vector3.Distance(_startTransform.position, mousePos);

        // 2. 타겟 설정 (거리가 한계치 이내일 때만 hit 인정)
        if (hit != null && dist <= limitDistance)
        {
            targetTransform = hit.transform;
            targetPos = targetTransform.position;
        }
        else
        {
            // 거리가 너무 멀면 hit이 있어도 허공으로 취급
            targetTransform = null;

            if (dist <= limitDistance)
            {
                // 1. 사거리 안쪽을 클릭했다면? 그 지점까지만 던짐
                targetPos = mousePos;
            }
            else
            {
                // 2. 사거리 밖을 클릭했다면? 방향은 유지하되 거리는 제한
                Vector3 dir = ((Vector3)mousePos - _startTransform.position).normalized;
                targetPos = _startTransform.position + dir * limitDistance;
            }
        }

        InitThread();

        // 3. 연결 가능 여부 최종 판별
        if (targetTransform != null) // 위에서 거리 체크를 통과한 경우에만 들어옴
        {
            var threadTarget = targetTransform.GetComponent<IThreadInteractable>();
            bool isCompatible = false;

            if (threadTarget != null)
                isCompatible = threadTarget.AllowedThreads.HasFlag(ConvertToFlag(this._threadType));

            if (isCompatible)
            {
                clickable = targetTransform.GetComponent<IClickInteractableToggle>();
                threadTarget.OnThreadHit(this._threadType);

                if (_endTransform != null)
                {
                    _endTransform.SetParent(targetTransform);
                    _endTransform.localPosition = Vector2.zero;
                }
                targetPos = targetTransform.position;

                StartCoroutine(Throwing(() =>
                {
                    _state = ThrowThreadState.Exist;
                    AudioManager.Instance?.PlaySfx(AudioManager.Sfx.LinkThread);
                    OnConnected?.Invoke();
                    /* 이 부분 상속처리함 */
                    ThrowingEvent();
                }));
            }
            else
            {
                // 호환되지 않는 실인 경우
                StartCoroutine(Throwing(StartDeleting));
            }
        }
        else
        {
            // 거리가 멀거나 맞은 게 없는 경우 (이때 원래대로 Deleting 상태로 넘어가며 아래로 떨어짐)
            StartCoroutine(Throwing(StartDeleting));
        }
    }

    private ThreadCompatibility ConvertToFlag(ThreadType state)
    {
        return state == ThreadType.Red ? ThreadCompatibility.Red : ThreadCompatibility.Blue;
    }

    protected virtual void ThrowingEvent() { }
    
    protected virtual void StartDeleting()
    {
        _state = ThrowThreadState.Deleting;
        if (_endTransform != null)
        {
            _endTransform.SetParent(null); // 중력 낙하를 시작하기 전 부모 관계를 안전하게 해제
        }
        OnDisconnected?.Invoke();
    }

    private IEnumerator Throwing(System.Action onComplete)
    {
        while (true)
        {
            if (_endTransform == null || !segments.IsCreated) yield break;

            float distToTarget = Vector3.Distance(_endTransform.position, targetPos);
            Vector3 dir = (targetPos - _endTransform.position).normalized;

            float step = Mathf.Min(_throwSpeed * Time.deltaTime, distToTarget);
            _endTransform.position += dir * step;

            if (segmentCount >= maxSegmentCount || distToTarget <= 0.01f)
            {
                if (_endTransform == null || !segments.IsCreated) yield break;

                _endTransform.position = targetPos;
                segments[maxSegmentCount - 1] = new Segment(_endTransform.position);
                segmentCount = maxSegmentCount;
                NormalizeSegments();
                onComplete?.Invoke();
                yield break;
            }
            AddSegments();

            yield return null;
        }
    }
    
    protected virtual void ResetAlpha()
    {
        if (_lineRenderer != null)
        {
            Color c = _lineRenderer.startColor;
            c.a = 1f;
            _lineRenderer.startColor = c;
            _lineRenderer.endColor = c;
        }
    }

    protected virtual void OnDisable()
    {
        if (_endTransform != null)
        {
            _endTransform.SetParent(null);
        }
    }

    public abstract bool IsExpired();
}